# Generated by Django 4.2 on 2023-05-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/content_image')),
            ],
        ),
    ]
