# Generated by Django 4.0.4 on 2023-05-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_blogcontents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontents',
            old_name='image',
            new_name='content_image',
        ),
    ]
