# Generated by Django 4.0.4 on 2023-05-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_image_blogcontents_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontents',
            name='blog_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blogcontents',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogcontents',
            name='content_image',
            field=models.ImageField(null=True, upload_to='media/content_image'),
        ),
    ]
